/* Generated By:JavaCC: Do not edit this line. DokaTreeConstants.java Version 7.0.11 */
package parser;

public interface DokaTreeConstants
{
  public int JJTMAIN = 0;
  public int JJTBLOCK = 1;
  public int JJTDECLARATION_STATEMENTS = 2;
  public int JJTMODULE_STATEMENTS = 3;
  public int JJTCOMMON_EXPRESSIONS = 4;
  public int JJTMODULE_IO_PARAMS = 5;
  public int JJTDECLARE_ASSIGNMENT = 6;
  public int JJTID = 7;
  public int JJTFUNCTIONAL_BLOCK = 8;
  public int JJTDECLARE_CONDITION = 9;
  public int JJTDECLARE_LAMBDA_FUNCTION = 10;
  public int JJTDECLARE_FUNCTION = 11;
  public int JJTDECLARE_LIST = 12;
  public int JJTDECLARE_CONDITIONAL_PARAMS = 13;
  public int JJTDECLARE_FUNCTION_PARAMS = 14;
  public int JJTRETURN_EXPRESSION = 15;
  public int JJTSTRING = 16;
  public int JJTBOOL = 17;
  public int JJTNUMBER = 18;
  public int JJTEXPRESSION = 19;
  public int JJTLOGICAL_EXPRESSION = 20;
  public int JJTNUMERICAL_EXPRESSION = 21;
  public int JJTCALLABLE_EXPRESSION = 22;
  public int JJTPRIORITY_EXPRESSION = 23;
  public int JJTLIST_EXPRESSION = 24;
  public int JJTBRACKETS_EXPRESSION = 25;


  public String[] jjtNodeName = {
    "Main",
    "block",
    "declaration_statements",
    "module_statements",
    "common_expressions",
    "module_io_params",
    "declare_assignment",
    "id",
    "functional_block",
    "declare_condition",
    "declare_lambda_function",
    "declare_function",
    "declare_list",
    "declare_conditional_params",
    "declare_function_params",
    "return_expression",
    "string",
    "bool",
    "number",
    "expression",
    "logical_expression",
    "numerical_expression",
    "callable_expression",
    "priority_expression",
    "list_expression",
    "brackets_expression",
  };
}
/* JavaCC - OriginalChecksum=d258b396b7ba891473bf00ef10272d79 (do not edit this line) */
