/* Generated By:JavaCC: Do not edit this line. DokaTreeConstants.java Version 5.0 */
public interface DokaTreeConstants
{
  public int JJTMAIN = 0;
  public int JJTBLOCK = 1;
  public int JJTFUNCTINAL_DECLARATION_BLOCK = 2;
  public int JJTDECLARATION_STATEMENTS = 3;
  public int JJTMODULE_STATEMENTS = 4;
  public int JJTCALLABLE_FUNCTION_STATEMENTS = 5;
  public int JJTDECLARE_ASSIGMENT = 6;
  public int JJTDECLARE_CONDITION = 7;
  public int JJTDECLARE_LAMBDA_FUNCTION = 8;
  public int JJTDECLARE_FUNCTION = 9;
  public int JJTDECLARE_LIST = 10;
  public int JJTDECLARE_CONDITIONAL_PARAMS = 11;
  public int JJTDECLARE_FUNCTION_PARAMS = 12;
  public int JJTRETURN_EXPRESSION = 13;
  public int JJTEXPRESSION = 14;
  public int JJTRIGHT_SIDE_EXPRESSION = 15;
  public int JJTCALLABLE_EXPRESSION = 16;
  public int JJTLOGICAL_EXPRESSION = 17;
  public int JJTMATHEMATICAL_EXPRESSION = 18;
  public int JJTPRIORITY_EXPRESSION = 19;
  public int JJTBRECKETS_EXPRESSION = 20;
  public int JJTLIST_EXPRESSION = 21;
  public int JJTMATH_OPERATOR = 22;
  public int JJTLOGIC_OPERATOR = 23;


  public String[] jjtNodeName = {
    "Main",
    "block",
    "functinal_declaration_block",
    "declaration_statements",
    "module_statements",
    "callable_function_statements",
    "declare_assigment",
    "declare_condition",
    "declare_lambda_function",
    "declare_function",
    "declare_list",
    "declare_conditional_params",
    "declare_function_params",
    "return_expression",
    "expression",
    "right_side_expression",
    "callable_expression",
    "logical_expression",
    "mathematical_expression",
    "priority_expression",
    "breckets_expression",
    "list_expression",
    "math_operator",
    "logic_operator",
  };
}
/* JavaCC - OriginalChecksum=3ba25f149ca9b3e8632b986d5de027d1 (do not edit this line) */
